# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BraytonCycleUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):


        #Default Params
        in_vel = 10
        in_temp = 20
        in_pres = 101.325
        in_diam = 0.5
        in_area_ratio = 1
        comp_pres_ratio = 30
        fuel_flow= 100
        turb_pres_ratio= 60
        noz_area_ratio = 1


        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 421))
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        
        self.Inlet = QtWidgets.QWidget()
        self.Inlet.setObjectName("Inlet")
        
        self.inletVelocity = QtWidgets.QLabel(self.Inlet)
        self.inletVelocity.setGeometry(QtCore.QRect(40, 70, 141, 16))
        self.inletVelocity.setObjectName("inletVelocity")
        
        self.velocityValue = QtWidgets.QLineEdit(self.Inlet)
        self.velocityValue.setGeometry(QtCore.QRect(220, 70, 121, 20))
        self.velocityValue.setObjectName("velocityValue")
        self.velocityValue.setText(str(in_vel))
        
        self.ambientTemp = QtWidgets.QLabel(self.Inlet)
        self.ambientTemp.setGeometry(QtCore.QRect(40, 130, 131, 16))
        self.ambientTemp.setObjectName("ambientTemp")
        
        self.tempValue = QtWidgets.QLineEdit(self.Inlet)
        self.tempValue.setGeometry(QtCore.QRect(220, 130, 121, 20))
        self.tempValue.setObjectName("tempValue")
        self.tempValue.setText(str(in_temp))

        self.ambientPres = QtWidgets.QLabel(self.Inlet)
        self.ambientPres.setGeometry(QtCore.QRect(40, 190, 111, 16))
        self.ambientPres.setObjectName("ambientPres")
        
        self.presValue = QtWidgets.QLineEdit(self.Inlet)
        self.presValue.setGeometry(QtCore.QRect(220, 190, 121, 20))
        self.presValue.setObjectName("presValue")
        self.presValue.setText(str(in_pres))
        
        self.intakeDiam = QtWidgets.QLabel(self.Inlet)
        self.intakeDiam.setGeometry(QtCore.QRect(410, 70, 111, 16))
        self.intakeDiam.setObjectName("intakeDiam")
        
        self.diamValue = QtWidgets.QLineEdit(self.Inlet)
        self.diamValue.setGeometry(QtCore.QRect(560, 70, 121, 20))
        self.diamValue.setObjectName("diamValue")
        self.diamValue.setText(str(in_diam))


        self.diffRatio = QtWidgets.QLabel(self.Inlet)
        self.diffRatio.setGeometry(QtCore.QRect(410, 130, 121, 16))
        self.diffRatio.setObjectName("diffRatio")
        
        self.diffRatioValue = QtWidgets.QLineEdit(self.Inlet)
        self.diffRatioValue.setGeometry(QtCore.QRect(560, 130, 121, 20))
        self.diffRatioValue.setObjectName("diffRatioValue")
        self.diffRatioValue.setText(str(in_area_ratio))

        self.nozzleRatio = QtWidgets.QLabel(self.Inlet)
        self.nozzleRatio.setGeometry(QtCore.QRect(320, 250, 121, 16))
        self.nozzleRatio.setObjectName("nozzleRatio")
        
        self.nozzleControl = QtWidgets.QSlider(self.Inlet)
        self.nozzleControl.setGeometry(QtCore.QRect(300, 290, 160, 22))
        self.nozzleControl.setOrientation(QtCore.Qt.Horizontal)
        self.nozzleControl.setObjectName("nozzleControl")
        
        self.nozzleControl.setRange(1,10)
        self.nozzleControl.valueChanged.connect(self.changeNozzle)

        self.nozzleValue = QtWidgets.QLCDNumber(self.Inlet)
        self.nozzleValue.setGeometry(QtCore.QRect(490, 290, 64, 23))
        self.nozzleValue.setObjectName("nozzleValue")
        
        self.tabWidget.addTab(self.Inlet, "")
        self.Compressor = QtWidgets.QWidget()
        self.Compressor.setObjectName("Compressor")
        
        self.compPresRatio = QtWidgets.QLabel(self.Compressor)
        self.compPresRatio.setGeometry(QtCore.QRect(60, 40, 251, 16))
        self.compPresRatio.setObjectName("compPresRatio")

        
        self.compControl = QtWidgets.QSlider(self.Compressor)
        self.compControl.setGeometry(QtCore.QRect(60, 90, 160, 22))
        self.compControl.setOrientation(QtCore.Qt.Horizontal)
        self.compControl.setObjectName("compControl")
        self.compControl.setRange(1, 50)
        self.compControl.valueChanged.connect(self.changeComp)


        self.compPresValue = QtWidgets.QLCDNumber(self.Compressor)
        self.compPresValue.setGeometry(QtCore.QRect(260, 90, 64, 23))
        self.compPresValue.setObjectName("compPresValue")
        
        self.airFuelRatio = QtWidgets.QLabel(self.Compressor)
        self.airFuelRatio.setGeometry(QtCore.QRect(510, 50, 141, 20))
        self.airFuelRatio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.airFuelRatio.setAlignment(QtCore.Qt.AlignCenter)
        self.airFuelRatio.setObjectName("airFuelRatio")
        
        self.AFRcontrol = QtWidgets.QSlider(self.Compressor)
        self.AFRcontrol.setGeometry(QtCore.QRect(570, 90, 22, 160))
        self.AFRcontrol.setOrientation(QtCore.Qt.Vertical)
        self.AFRcontrol.setObjectName("AFRcontrol")
        self.AFRcontrol.setRange(50,150)
        self.AFRcontrol.valueChanged.connect(self.changeAFR)
        
        self.AFRdisplay = QtWidgets.QLCDNumber(self.Compressor)
        self.AFRdisplay.setGeometry(QtCore.QRect(550, 270, 64, 23))
        self.AFRdisplay.setObjectName("AFRdisplay")
        self.AFRdisplay.display(150)
        
        self.turbPresRatio = QtWidgets.QLabel(self.Compressor)
        self.turbPresRatio.setGeometry(QtCore.QRect(60, 160, 171, 16))
        self.turbPresRatio.setObjectName("turbPresRatio")
        
        self.turbControl = QtWidgets.QSlider(self.Compressor)
        self.turbControl.setGeometry(QtCore.QRect(60, 210, 160, 22))
        self.turbControl.setOrientation(QtCore.Qt.Horizontal)
        self.turbControl.setObjectName("turbControl")
        self.turbControl.setRange(1,150)
        self.turbControl.valueChanged.connect(self.changeTurb)


        self.turbPresValue = QtWidgets.QLCDNumber(self.Compressor)
        self.turbPresValue.setGeometry(QtCore.QRect(260, 210, 64, 23))
        self.turbPresValue.setObjectName("turbPresValue")
        
        self.tabWidget.addTab(self.Compressor, "")
        self.Assumptions = QtWidgets.QWidget()
        self.Assumptions.setObjectName("Assumptions")
        
        self.scrollArea = QtWidgets.QScrollArea(self.Assumptions)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 771, 381))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 769, 379))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        
        self.tabWidget.addTab(self.Assumptions, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inletVelocity.setText(_translate("MainWindow", "Air Velocity [m/s]"))
        self.ambientTemp.setText(_translate("MainWindow", "Ambient Temperature [°C]"))
        self.ambientPres.setText(_translate("MainWindow", "Ambient Pressure [kPa]"))
        self.intakeDiam.setText(_translate("MainWindow", "Intake Diameter [m]"))
        self.diffRatio.setText(_translate("MainWindow", "Diffuser Area Ratio x:1"))
        self.nozzleRatio.setText(_translate("MainWindow", "Nozzle Area Ratio x:1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Inlet), _translate("MainWindow", "Inlet/Outlet"))
        self.compPresRatio.setText(_translate("MainWindow", "Compressor Pressure Ratio 1:x"))
        self.airFuelRatio.setText(_translate("MainWindow", "Air Fuel Ratio x:1"))
        self.turbPresRatio.setText(_translate("MainWindow", "Turbine Pressure Ratio x:1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Compressor), _translate("MainWindow", "Compressor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Assumptions), _translate("MainWindow", "Assumptions"))


    def changeAFR(self, value):
        self.AFRdisplay.display(200-value)


    def changeComp(self, value):
        self.compPresValue.display(value)

    def changeTurb(self,value):
        self.turbPresValue.display(value)
    
    def changeNozzle(self,value):
        self.nozzleValue.display(value)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
